"""GNOME Shell renderer - converts universal tokens to shell CSS."""

import datetime
from pathlib import Path

from ..tokens.schema import UniversalTokenSchema
from ..color.spaces import Color
from .base import BaseRenderer, RenderedTheme


class GnomeShellRenderer(BaseRenderer):
    """Render universal tokens to GNOME Shell CSS configuration."""

    def render(self, tokens: UniversalTokenSchema) -> RenderedTheme:
        """Generate GNOME Shell CSS content from universal tokens."""
        css_content = self._generate_shell_css(tokens)

        return RenderedTheme(
            toolkit="gnome-shell",
            files={Path("gnome-shell/gnome-shell-custom.css"): css_content},
            settings={"theme-name": tokens.name},
        )

    def _generate_shell_css(self, tokens: UniversalTokenSchema) -> str:
        """Build shell CSS using universal token values."""
        css_parts = [
            "/* Generated by Unified Theming App */",
            f"/* Theme: {tokens.name} ({tokens.variant}) */",
            f"/* Timestamp: {datetime.datetime.now()} */",
            "",
            "/* Color Variables */",
        ]

        shell_colors = {
            "panel_bg_color": self._color_hex(tokens.surfaces.primary),
            "panel_fg_color": self._color_hex(tokens.content.primary),
            "panel_border_color": self._color_hex(tokens.borders.default),
            "dialog_bg_color": self._color_hex(tokens.surfaces.elevated),
            "dialog_fg_color": self._color_hex(tokens.content.primary),
            "selected_bg_color": self._color_hex(tokens.accents.primary),
            "selected_fg_color": self._color_hex(tokens.content.inverse),
            "success_color": self._color_hex(tokens.accents.success),
            "warning_color": self._color_hex(tokens.accents.warning),
            "error_color": self._color_hex(tokens.accents.error),
        }

        for color_name, color_value in shell_colors.items():
            css_parts.append(f"@define-color {color_name} {color_value};")

        css_parts.extend(["", "/* Panel Styling */"])

        css_parts.extend(
            [
                "#panel {",
                f"  background-color: {shell_colors['panel_bg_color']};",
                f"  color: {shell_colors['panel_fg_color']};",
                f"  border-bottom: 1px solid {shell_colors['panel_border_color']};",
                "}",
            ]
        )

        css_parts.extend(
            [
                "",
                "/* Overview Styling */",
                ".workspace-background {",
                f"  background-color: {shell_colors['dialog_bg_color']};",
                "}",
            ]
        )

        css_parts.extend(
            [
                "",
                "/* Selection Styling */",
                ".selected, :focus {",
                f"  background-color: {shell_colors['selected_bg_color']};",
                f"  color: {shell_colors['selected_fg_color']};",
                "}",
            ]
        )

        css_parts.extend(
            [
                "",
                "/* Popup Menu Styling */",
                ".popup-menu-content {",
                f"  background-color: {shell_colors['dialog_bg_color']};",
                f"  color: {shell_colors['dialog_fg_color']};",
                "}",
            ]
        )

        return "\n".join(css_parts)

    def _color_hex(self, color: Color) -> str:
        """Convert Color objects to hex strings."""
        return color.to_hex()
